package giusti.felipe.enums;

public enum ProfissoesEnum {
    ALQUIMISTA, ARQUEIRO, FERREIRO, MINERADOR, VENDEDOR, ESPADACHIM, MAGO, SACERDOTE, CAVALEIRO, LADRAO, INVOCADOR, GUERREIRO, BRUXO, CACADOR, PALADINO
}
